name: Java CI

on: 
  push:
    branches:
      - master
      - test


jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./RobotCode/
      
  #docs:
   # runs-on: [windows-latest]
    #timeout-minutes: 5
    #needs: [build]
    #steps:
     # - uses: actions/checkout@v1
      #- name: run doxygen
       # run: ./doxygen/doxygen.exe ./doxygen/testconfig 
      #- uses: actions/commit@v1
    
    
